[package]
name = "derive"
version = "0.1.0"
authors = ["Mick van Gelderen <mickvangelderen@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "*", features = ["extra-traits"] }
# syn = "*"
# proc-macro2 = "*"
quote = "*"
