[package]
name = "log-viewer"
version = "0.1.0"
authors = ["Mick van Gelderen <mickvangelderen@gmail.com>"]
edition = "2018"

[[bin]]
name = "log-viewer"
path = "log-viewer.rs"

[dependencies]
renderer = { path = "../renderer" }
