[package]
name = "polygen"
version = "0.1.0"
authors = ["Mick van Gelderen <mickvangelderen@gmail.com>"]
edition = "2018"

[lib]
path = "polygen.rs"

[dependencies]

[dev-dependencies]
criterion = "0.2.10"

[[bench]]
name = "polygen"
harness = false
