[package]
name = "polygen"
version = "0.1.0"
authors = ["Mick van Gelderen <mickvangelderen@gmail.com>"]
edition = "2018"

[dependencies]
cgmath = "0.17.0"

[dev-dependencies]
criterion = "0.2.10"

[[bench]]
name = "polygen"
harness = false
